# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{randomizer}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Canavese"]
  s.date = %q{2009-11-20}
  s.description = %q{}
  s.email = %q{paul@canavese.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "data/female_first_names.txt",
     "data/last_names.txt",
     "data/male_first_names.txt",
     "data/text/aesop.txt",
     "data/text/alice_in_wonderland.txt",
     "data/text/lorem_ipsum.txt",
     "data/text/the_adventures_of_sherlock_holmes.txt",
     "features/randomizer.feature",
     "features/step_definitions/randomizer_steps.rb",
     "features/support/env.rb",
     "lib/randomizer.rb",
     "lib/randomizer/all_avatars_site.rb",
     "lib/randomizer/markov_text_generator.rb",
     "lib/randomizer/name_generator.rb",
     "lib/randomizer/random_user.rb",
     "randomizer.gemspec",
     "spec/randomizer_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/canavese/randomizer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Generates random test data}
  s.test_files = [
    "spec/randomizer_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<nokogiri>, [">= 1.3.3"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 1.3.3"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 1.3.3"])
  end
end

